sam-tripathi/Defeat-JAVA

- SIMPLE PROJECTS/BANKING-APPLICATION/Bank.java
- SIMPLE PROJECTS/BANKING-APPLICATION/Branch.java
- SIMPLE PROJECTS/BANKING-APPLICATION/Customer.java
- SIMPLE PROJECTS/BANKING-APPLICATION/Description.md
- SIMPLE PROJECTS/BANKING-APPLICATION/Main.java
Created and added a simple command-line banking application demonstrating the concept of _Interface_
> Created Banking Application

- DSA-Beginners resource guide
This is just an outline not the main file.
> Create DSA-Beginners resource guide

- EXTERNAL RESOURCES FOR JAVA.md
Added a External Resources for Java beginners
> Learn Java from Free Resources

- CODE_OF_CONDUCT.md
Delete the existing `CONTRIBUTOR_CONVENT _CODE_OF_CONDUCT.md` file after merging.
> Issue #16 solution

- SIMPLE PROJECTS/SpringSample/README.md
Hi!. I've updated the project with a proper **README.md** with installation instructions and Working.
Please merge and label with accepted if checks meet.
> Add README.md

- SIMPLE PROJECTS/BMI Calculator/main.java
Closes #9 
Added a simple java program which can calculate a person's BMI based on his height and weight.
The program can work in both the SI unit system and the CGS unit system.
Screenshot:
> Added BMI Calculator

- SIMPLE PROJECTS/Beginner Java/BinarySearch.java
- SIMPLE PROJECTS/Beginner Java/BubbleSort.java
- SIMPLE PROJECTS/Beginner Java/Factorial_ofnumber.java
- SIMPLE PROJECTS/Beginner Java/Fibonacci_series.java
- SIMPLE PROJECTS/Beginner Java/InsertionSort.java
- SIMPLE PROJECTS/Beginner Java/Is_Armstrong.java
- SIMPLE PROJECTS/Beginner Java/Is_Pallindrome.java
- SIMPLE PROJECTS/Beginner Java/LinearSearch.java
- SIMPLE PROJECTS/Beginner Java/PrimeNumber.java
- SIMPLE PROJECTS/Beginner Java/SelectionSort.java
Searching and Sorting Programs
Basic Numbers programs
Series Programs
> Added some Beginner Programs in JAVA

- DataStructures/SortingAlgorithms/bubbleSort.java
- DataStructures/SortingAlgorithms/insertionSort.java
- DataStructures/SortingAlgorithms/searchingSort.java
I have made a folder under Data Structures and added bubble, selection and insertion sort algorithms.
#37 
Can you check the PR?
> Sorting Algorithms added

- PROBLEMS/Exceptional_handeling.java
Example of Exceptional Handling in Java
> Exceptional Handling in Java

- DSA-RoadmapAndTutorials/RoadMap
- DSA-RoadmapAndTutorials/Tutorials
pls check the PR and comment if any changes to ge made
if no changes to be made then pls merge it under hacktoberfest-accepted label!
> DSA-roadmap and tutorials

- PROBLEMS/calculator problem/Mathematics Problem/GCD.java
> GCD by JAVA

- PROBLEMS/Exception Handling/Java Exceptions Explained.java
This code explains basics of exception handling and how and why we use them.
> Java Exceptions Explained.java

- PROBLEMS/Polymorphism/Polymorphism Explained.java
Polymorphism and its types are explained with real-world examples and code.
> Polymorphism Explained

- DataStructures/Recursion/Leetcode/count_opearation_zero.java
- DataStructures/Recursion/Leetcode/make_it_zero.java
- DataStructures/Recursion/understand/Main.java
- DataStructures/Recursion/understand/binary_search.java
- DataStructures/Recursion/understand/concept.java
- DataStructures/Recursion/understand/print_number.java
- DataStructures/Recursion/understand/sum_digits.java
Please check and review it and add a hactoberfest tag
> Add a recursion folder

- DataStructures/BinaryTree.java
Added Binary Tree Implementaion Code Kindly Merge it.
> Binary Tree Implementaion Code- Added

- DataStructures/Bipartite_BSF.cpp
BFS to check graph is bipartite or not
> BFS to check graph is bipartite or not

- DataStructures/DFS_bipartite.cpp
DFS to check graph is bipartite or not
> DFS to check graph is bipartite or not

- DataStructures/Recursion/understand/Return array of indices of an element in array
This program return the indices of a recurring element in array.
> Return array of indices of an element in array

- DataStructures/SearchingAlgorithms/Jump_Search.java
> Added Jump_Search Algorithm Program

- SOLUTIONS/GDOG.java
- SOLUTIONS/HEADBOB.java
- SOLUTIONS/HEIGHTS.java
- SOLUTIONS/HS08TEST.java
- SOLUTIONS/INFERNO.java
- SOLUTIONS/INTEST.java
- SOLUTIONS/INTRDSGN.java
- SOLUTIONS/KSUB.java
- SOLUTIONS/LAPIN.java
- SOLUTIONS/LAPTOPREC.java
- SOLUTIONS/LARGEFAM.java
- SOLUTIONS/LASTLEVELS.java
- SOLUTIONS/LEAGUE.java
- SOLUTIONS/MAKEABEQUAL.java
- SOLUTIONS/MAKEPALAGAIN.java
- SOLUTIONS/MASKPOL.java
- SOLUTIONS/MAX01EVSWP.java
- SOLUTIONS/MAXORMIN.java
- SOLUTIONS/MAXTHEMIN.java
- SOLUTIONS/MEANMAX.java
- SOLUTIONS/MEDMAXMATCH.java
- SOLUTIONS/MEET.java
- SOLUTIONS/MINCOINSREQ.java
- SOLUTIONS/MINFD.java
- SOLUTIONS/MINFLIPS.java
- SOLUTIONS/MISS_NUM.java
Added another 26 files via upload
> Added CodeChef Solutions

- AttendanceGenerator.java
- Publisher.java
- Quantitysort.java
Basic Java Files to help beginners
> Basic Java Files

- Object &Classes/Bike.java
- Object &Classes/Cat.java
- Object &Classes/SimpleClass.java
- Object &Classes/SimpleObject.java
- Object &Classes/Student.java
- Object &Classes/Test.java
Added descriptive programs of Object and Classes of Java
> Basic Java Porgrams of Object and Classes

- DataStructures/TrieDictionary/Dictionary.java
- DataStructures/TrieDictionary/Main.java
- DataStructures/TrieDictionary/Node.java
- Use Hashmap to create Trie Node
- Sample Main Application to try and test Trie
- Functions:
- Insert String
- Search String
> Add Trie Dictionary implementation in Java

- SOLUTIONS/scramblies.java
- SOLUTIONS/split et regex.txt
> feat : add scramblies for array in java(hacktoberfest)

- DataStructures/SearchingAlgorithms/Exponential Search.java
Exponential search allows for searching through a sorted, unbounded list for a specified input value (the search "key"). The algorithm consists of two stages. The first stage determines a range in which the search key would reside if it were in the list. In the second stage, a binary search is performed on this range.
Hey i have contributed by making exponential search in java please accept my pull request and give me the label of hacktoberfest
> Create Exponential Search.java

- DataStructures/Radixsort.java
> Radix Sort

- DataStructures/SearchingAlgorithms/OrderAgnosticBinSearch.java
Added the Order Agnostic Binary Search java program in Data Structures/SearchingAlgorithms directory.
Let me know if any edits are to be made before merge.
> Added Order Agnostic Binary Search Program

- SOLUTIONS/JavaCodewars/SumByFactors.java
> add binary tree code and kyu4 solution codewars sumbyfactor
